### ISSUE TITLE
Навигация по городам через anchor

### ISSUE THREAD

**Issue by IgorKonovalov** [solarrust/junior-friendly#13]
Предлагаю сделать навигацию по городам простейшим списком в шапке. 
`[Кукуево](#kukuevo) -> <a name="kukuevo">Вакансии в Кукуево</a>`

**Comment by solarrust** [comment]
Отличная идея!
Спасибо, реализую чуть позже.

**Comment by solarrust** [comment]
Реализована навигация по городам в файле city.md
