### ISSUE TITLE
Junior friendly ли Тинькофф? 

### ISSUE THREAD

**Issue by verbaux** [solarrust/junior-friendly#14]
Можно подробностей про стажировку от Тинькоффа? Пока они даже не отвечают на письма о работе, либо сразу присылают отказы.

**Comment by solarrust** [comment]
У меня нет подробностей о стажировке от Тинькофф. Вся информация, которая мне известна размещена в списке.

**Comment by tsergeytovarov** [comment]
@verbaux а вы про стажировку или про вакансию, которая идёт в списке?

**Comment by verbaux** [comment]
Ой да, прошу прощения за некорректную формулировку, речь именно о вакансии.

**Comment by tsergeytovarov** [comment]
Если они один раз прислали вам отказ, значит второй раз тоже пришлют отказ. И у вас как то странно сформулировано, они не отвечают на письма, но при этом присылают отказы? Можно подробнее про то, что вы делали? Может у вас есть статистика по нескольким людям?

**Comment by verbaux** [comment]
На эмоциях писал :( а эмоции — плохой советчик. Первый ишью комом :( Спасибо вам за терпение, и попытку прояснить ситуацию!!! 

Троих знаю лично, двоим не ответили, одному прислали отказ без объяснения причин. Может быть я слишком много хочу, но кажется, что джуниор-френдли компания не должна так поступать. Если я не прав — приношу свои извинения за беспочвенный ишью.

**Comment by alexdeia** [comment]
А разве часто отказывают с объяснениями причин?

**Comment by verbaux** [comment]
Нет, не часто — и это очень плохо. Особенно когда было выполнено тестовое задание. Но с обычных компаний какой спрос — им нужно найти специалиста с наименьшими издержками, и они плевать хотели на времязатраты потенциального работника. 

Но вот могут ли так же поступать компании, заявившие (в этот список же не попадают просто потому, что автору захотелось), что они "джуниор-френдли"?

**Comment by alexdeia** [comment]
"джуниор-френдли", как по мне, это и есть те компании, которые хотят получить побольше умов по низкой стоимости, прикрываясь этой самой формулировкой. Впрочем, как и большинство других компаний.

**Comment by fyvfyv** [comment]
Кмк, «джуниор-френдли», это те компании, которые готовы брать себе джунов на стажировки/работы. Но при этом, это не означает, что они должны бегать за каждым джуном и рассказывать ему, чем он так не понравился компании. Тем более это банк и там не только интеллектуальную часть проверяют, но и прочие личностные качества и биографию.

**Comment by tsergeytovarov** [comment]
@verbaux @solarrust 
> Троих знаю лично, двоим не ответили, одному прислали отказ без объяснения причин. Может быть я слишком много хочу, но кажется, что джуниор-френдли компания не должна так поступать.

Компания которая находится в этом списке, конечно не должна так поступать. С другой стороны, каждая компания работает по разному, кто то присылает мотивированный отказ, кто-то не считает нужным вообще отвечать на сообщения. Конечно, мы можем найти компанию, которая утверждает, что она готова работать с новичками, но изменить сам подход к работе компании с резюме мы не можем. Возможно те резюме показались им слишком слабыми.

Мы постараемся выяснить где тут истина, но поймите как работает этот список. Компания пишет и предлагает нам вакансию. Мы её размещаем. Дальше вы пробуете попасть в эту компанию и если встречаетесь с какими-то проблемами, вы пишите нам. Если мы считаем что эти проблемы не совместимы со статусом "junior fliendly", то компания будет вычекнута из списка. Писать в компанию со словами, почему вы не отвечаете новичкам мы не можем. Так что ваш фидбэк нам просто необходим и спасибо, что вы его дали. Но лучше сразу описывать ситуацию целиком.

**Comment by verbaux** [comment]
Еще раз прошу прощения за пространное объяснение, и спасибо вам за ответы.

**Comment by solarrust** [comment]
Вакансия в Тинькофф-банк закрыта. Предлагаю вернуться к вопросу если эта компания повторно разместит свою вакансию в нашем списке.
